# fly.toml file generated for remix-jokes-v1 on 2023-04-17T22:14:03-07:00

app = "remix-jokes-v1"
primary_region = "lax"

[experimental]
  cmd = ["start_with_migrations.sh"]
  entrypoint = ["sh"]

[env]
  DATABASE_URL = "file:/data/sqlite.db"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true

[[mounts]]
  source = "data"
  destination = "/data"

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
